# constants
int8 UP = 1
int8 DOWN = 2

# Request
string line_id
int8 source_floor
int8 direction

---

# response constants
bool SUCCESS = true
bool FAILED  = false

# Responce
bool result

# true : call succeed
# false : call failed
